apiVersion: v1
kind: Service

metadata:
  name: crewai-api
  namespace: crewai
spec:
  type: NodePort
  selector:
    app: crewai-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30081