apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crewai-ingress
  namespace: crewai
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: crewai-api
                port:
                  number: 8000
          - path: /ollama(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: crewai-ollama
                port:
                  number: 11434
